const uint8_t MAC_RECEIVER[] = { 0x0C, 0xB8, 0x15, 0xD7, 0xE5, 0x38 };

enum CONTROL_STATE {
    NO_ACTION = 0,
    BLUE_PUNCH = 1,
    BLUE_BODY_KICK = 2,
    BLUE_HEAD_KICK = 3,
    BLUE_BODY_TECHNICAL_KICK = 4,
    BLUE_HEAD_TECHNICAL_KICK = 5,
    RED_PUNCH = 6,
    RED_BODY_KICK = 7,
    RED_HEAD_KICK = 8,
    RED_BODY_TECHNICAL_KICK = 9,
    RED_HEAD_TECHNICAL_KICK = 10,
};

enum SYSTEM_MODE {
    ONE_CONTROL = 0,
    TWO_CONTROL = 1,
    JUST_TRUNK_PROTECTOR = 2,
    TRUNK_PROTECTOR_AND_CONTROL = 3
};